generate:
  python3 setup.py generate

build: generate
  shiv -c muicore -o dist/muicore_server --reproducible --no-modify --python '/usr/bin/env python3.9' --compressed .
  #wget https://github.com/ethereum/solc-bin/blob/gh-pages/linux-amd64/solc-linux-amd64-v0.8.12%2Bcommit.f00d7308 -O dist/solc
  #chmod 775 dist/solc

install: build
  cp dist/* ../MUI/os/linux_x86_64/
