# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MUI.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='MUI.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\tMUI.proto\"\x16\n\x04UUID\x12\x0e\n\x06hexstr\x18\x01 \x01(\t\"&\n\x11ManticoreInstance\x12\x11\n\x02id\x18\x02 \x01(\x0b\x32\x05.UUID\"\x94\x01\n\x11TerminateResponse\x12\x32\n\x06status\x18\x03 \x01(\x0e\x32\".TerminateResponse.TerminateStatus\"K\n\x0fTerminateStatus\x12\x0b\n\x07SUCCESS\x10\x00\x12\x13\n\x0f\x41LREADY_STOPPED\x10\x01\x12\x16\n\x12INSTANCE_NOT_FOUND\x10\x02\"\x1c\n\x0c\x43LIArguments\x12\x0c\n\x04\x61rgs\x18\x04 \x03(\t\"\xa5\x01\n\x0e\x41\x64\x64ressRequest\x12*\n\x0emcore_instance\x18\x05 \x01(\x0b\x32\x12.ManticoreInstance\x12\x0f\n\x07\x61\x64\x64ress\x18\x06 \x01(\x04\x12(\n\x04type\x18\x07 \x01(\x0e\x32\x1a.AddressRequest.TargetType\",\n\nTargetType\x12\x08\n\x04\x46IND\x10\x00\x12\t\n\x05\x41VOID\x10\x01\x12\t\n\x05\x43LEAR\x10\x02\"\x8a\x01\n\x0eTargetResponse\x12,\n\x06status\x18\x08 \x01(\x0e\x32\x1c.TargetResponse.TargetStatus\"J\n\x0cTargetStatus\x12\x0b\n\x07SUCCESS\x10\x00\x12\x15\n\x11\x41\x44\x44RESS_NOT_FOUND\x10\x01\x12\x16\n\x12INSTANCE_NOT_FOUND\x10\x02\x32\xa7\x01\n\x0bManticoreUI\x12\x35\n\tTerminate\x12\x12.ManticoreInstance\x1a\x12.TerminateResponse\"\x00\x12,\n\x05Start\x12\r.CLIArguments\x1a\x12.ManticoreInstance\"\x00\x12\x33\n\rTargetAddress\x12\x0f.AddressRequest\x1a\x0f.TargetResponse\"\x00\x62\x06proto3'
)



_TERMINATERESPONSE_TERMINATESTATUS = _descriptor.EnumDescriptor(
  name='TerminateStatus',
  full_name='TerminateResponse.TerminateStatus',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SUCCESS', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ALREADY_STOPPED', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='INSTANCE_NOT_FOUND', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=151,
  serialized_end=226,
)
_sym_db.RegisterEnumDescriptor(_TERMINATERESPONSE_TERMINATESTATUS)

_ADDRESSREQUEST_TARGETTYPE = _descriptor.EnumDescriptor(
  name='TargetType',
  full_name='AddressRequest.TargetType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='FIND', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='AVOID', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CLEAR', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=380,
  serialized_end=424,
)
_sym_db.RegisterEnumDescriptor(_ADDRESSREQUEST_TARGETTYPE)

_TARGETRESPONSE_TARGETSTATUS = _descriptor.EnumDescriptor(
  name='TargetStatus',
  full_name='TargetResponse.TargetStatus',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SUCCESS', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ADDRESS_NOT_FOUND', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='INSTANCE_NOT_FOUND', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=491,
  serialized_end=565,
)
_sym_db.RegisterEnumDescriptor(_TARGETRESPONSE_TARGETSTATUS)


_UUID = _descriptor.Descriptor(
  name='UUID',
  full_name='UUID',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='hexstr', full_name='UUID.hexstr', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=13,
  serialized_end=35,
)


_MANTICOREINSTANCE = _descriptor.Descriptor(
  name='ManticoreInstance',
  full_name='ManticoreInstance',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='ManticoreInstance.id', index=0,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=37,
  serialized_end=75,
)


_TERMINATERESPONSE = _descriptor.Descriptor(
  name='TerminateResponse',
  full_name='TerminateResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='TerminateResponse.status', index=0,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _TERMINATERESPONSE_TERMINATESTATUS,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=78,
  serialized_end=226,
)


_CLIARGUMENTS = _descriptor.Descriptor(
  name='CLIArguments',
  full_name='CLIArguments',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='args', full_name='CLIArguments.args', index=0,
      number=4, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=228,
  serialized_end=256,
)


_ADDRESSREQUEST = _descriptor.Descriptor(
  name='AddressRequest',
  full_name='AddressRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='mcore_instance', full_name='AddressRequest.mcore_instance', index=0,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='address', full_name='AddressRequest.address', index=1,
      number=6, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='type', full_name='AddressRequest.type', index=2,
      number=7, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _ADDRESSREQUEST_TARGETTYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=259,
  serialized_end=424,
)


_TARGETRESPONSE = _descriptor.Descriptor(
  name='TargetResponse',
  full_name='TargetResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='TargetResponse.status', index=0,
      number=8, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _TARGETRESPONSE_TARGETSTATUS,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=427,
  serialized_end=565,
)

_MANTICOREINSTANCE.fields_by_name['id'].message_type = _UUID
_TERMINATERESPONSE.fields_by_name['status'].enum_type = _TERMINATERESPONSE_TERMINATESTATUS
_TERMINATERESPONSE_TERMINATESTATUS.containing_type = _TERMINATERESPONSE
_ADDRESSREQUEST.fields_by_name['mcore_instance'].message_type = _MANTICOREINSTANCE
_ADDRESSREQUEST.fields_by_name['type'].enum_type = _ADDRESSREQUEST_TARGETTYPE
_ADDRESSREQUEST_TARGETTYPE.containing_type = _ADDRESSREQUEST
_TARGETRESPONSE.fields_by_name['status'].enum_type = _TARGETRESPONSE_TARGETSTATUS
_TARGETRESPONSE_TARGETSTATUS.containing_type = _TARGETRESPONSE
DESCRIPTOR.message_types_by_name['UUID'] = _UUID
DESCRIPTOR.message_types_by_name['ManticoreInstance'] = _MANTICOREINSTANCE
DESCRIPTOR.message_types_by_name['TerminateResponse'] = _TERMINATERESPONSE
DESCRIPTOR.message_types_by_name['CLIArguments'] = _CLIARGUMENTS
DESCRIPTOR.message_types_by_name['AddressRequest'] = _ADDRESSREQUEST
DESCRIPTOR.message_types_by_name['TargetResponse'] = _TARGETRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

UUID = _reflection.GeneratedProtocolMessageType('UUID', (_message.Message,), {
  'DESCRIPTOR' : _UUID,
  '__module__' : 'MUI_pb2'
  # @@protoc_insertion_point(class_scope:UUID)
  })
_sym_db.RegisterMessage(UUID)

ManticoreInstance = _reflection.GeneratedProtocolMessageType('ManticoreInstance', (_message.Message,), {
  'DESCRIPTOR' : _MANTICOREINSTANCE,
  '__module__' : 'MUI_pb2'
  # @@protoc_insertion_point(class_scope:ManticoreInstance)
  })
_sym_db.RegisterMessage(ManticoreInstance)

TerminateResponse = _reflection.GeneratedProtocolMessageType('TerminateResponse', (_message.Message,), {
  'DESCRIPTOR' : _TERMINATERESPONSE,
  '__module__' : 'MUI_pb2'
  # @@protoc_insertion_point(class_scope:TerminateResponse)
  })
_sym_db.RegisterMessage(TerminateResponse)

CLIArguments = _reflection.GeneratedProtocolMessageType('CLIArguments', (_message.Message,), {
  'DESCRIPTOR' : _CLIARGUMENTS,
  '__module__' : 'MUI_pb2'
  # @@protoc_insertion_point(class_scope:CLIArguments)
  })
_sym_db.RegisterMessage(CLIArguments)

AddressRequest = _reflection.GeneratedProtocolMessageType('AddressRequest', (_message.Message,), {
  'DESCRIPTOR' : _ADDRESSREQUEST,
  '__module__' : 'MUI_pb2'
  # @@protoc_insertion_point(class_scope:AddressRequest)
  })
_sym_db.RegisterMessage(AddressRequest)

TargetResponse = _reflection.GeneratedProtocolMessageType('TargetResponse', (_message.Message,), {
  'DESCRIPTOR' : _TARGETRESPONSE,
  '__module__' : 'MUI_pb2'
  # @@protoc_insertion_point(class_scope:TargetResponse)
  })
_sym_db.RegisterMessage(TargetResponse)



_MANTICOREUI = _descriptor.ServiceDescriptor(
  name='ManticoreUI',
  full_name='ManticoreUI',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=568,
  serialized_end=735,
  methods=[
  _descriptor.MethodDescriptor(
    name='Terminate',
    full_name='ManticoreUI.Terminate',
    index=0,
    containing_service=None,
    input_type=_MANTICOREINSTANCE,
    output_type=_TERMINATERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Start',
    full_name='ManticoreUI.Start',
    index=1,
    containing_service=None,
    input_type=_CLIARGUMENTS,
    output_type=_MANTICOREINSTANCE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='TargetAddress',
    full_name='ManticoreUI.TargetAddress',
    index=2,
    containing_service=None,
    input_type=_ADDRESSREQUEST,
    output_type=_TARGETRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_MANTICOREUI)

DESCRIPTOR.services_by_name['ManticoreUI'] = _MANTICOREUI

# @@protoc_insertion_point(module_scope)
